# Generated by Django 5.2.3 on 2026-10-04 15:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0024_alter_registroobservador_subtipo'),
        ('salon_digital', '0002_paginapublicada_comentarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Nombre del examen')),
                ('fecha', models.DateField(verbose_name='Fecha de aplicación')),
                ('numero_preguntas', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('numero_opciones', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)], verbose_name='Opciones por pregunta')),
                ('hojas_por_pagina', models.PositiveSmallIntegerField(choices=[(1, '1 por página'), (2, '2 por página'), (4, '4 por página'), (8, '8 por página')], default=1)),
                ('metodo', models.CharField(choices=[('con_piso', 'Con piso: 0 aciertos saca la nota mínima'), ('proporcional', 'Proporcional: 0 aciertos saca 0 (se ajusta a la mínima)'), ('descuento', 'Por descuento: arranca en la máxima y resta')], default='con_piso', max_length=14, verbose_name='Cómo se calcula la nota')),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=4)),
                ('nota_minima', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('nota_todo_mal', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Nota de quien marca todo mal')),
                ('nota_nada_marcado', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=4, verbose_name='Nota de quien no marca nada')),
                ('componente', models.CharField(choices=[('SER', 'SER'), ('SABER', 'SABER'), ('HACER', 'HACER')], default='SABER', help_text='Si alguna pregunta tiene su propio componente, el examen se parte en varias columnas, una por componente.', max_length=6, verbose_name='A qué columna de la planilla va')),
                ('archivado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.asignaciondocente', verbose_name='Asignatura y curso')),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_puntoexacto', to='notas.colegio')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_puntoexacto', to='salon_digital.cuenta')),
                ('cursos', models.ManyToManyField(blank=True, related_name='examenes_puntoexacto', to='notas.curso', verbose_name='Cursos donde se aplica')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_puntoexacto', to='notas.docente')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.periodoacademico')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Hoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libre', models.CharField(blank=True, max_length=160)),
                ('documento_libre', models.CharField(blank=True, max_length=40)),
                ('identificador', models.CharField(help_text='Lo que va en el código de barras.', max_length=40, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Sin calificar'), ('calificada', 'Calificada'), ('revisar', 'Necesita revisión'), ('ausente', 'No presentó')], default='pendiente', max_length=12)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_recortada', models.BooleanField(default=False, help_text='La nota calculada se salía de la escala y se ajustó.')),
                ('enviada_a_planilla', models.BooleanField(default=False)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hojas_puntoexacto', to='notas.estudiante')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas', to='puntoexacto.examen')),
            ],
            options={
                'verbose_name': 'Hoja',
                'verbose_name_plural': 'Hojas',
                'ordering': ['estudiante__user__last_name', 'nombre_libre'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('correcta', models.CharField(blank=True, max_length=1, verbose_name='Respuesta correcta')),
                ('puntos', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('parciales', models.JSONField(blank=True, default=dict, verbose_name='Opciones con crédito parcial')),
                ('etiquetas', models.CharField(blank=True, help_text='Separadas por coma. Se repiten entre preguntas a propósito: así se agrupan en el análisis.', max_length=200, verbose_name='Qué evalúa')),
                ('componente', models.CharField(blank=True, choices=[('SER', 'SER'), ('SABER', 'SABER'), ('HACER', 'HACER')], help_text='Vacío = el del examen. Permite que un mismo examen evalúe SABER en unas preguntas y HACER en otras.', max_length=6, verbose_name='Componente')),
                ('anulada', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='puntoexacto.examen')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('examen', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcada', models.CharField(blank=True, max_length=1)),
                ('hoja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='puntoexacto.hoja')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='puntoexacto.pregunta')),
            ],
            options={
                'ordering': ['pregunta__numero'],
                'unique_together': {('hoja', 'pregunta')},
            },
        ),
    ]
