# Generated by Django 5.2.3 on 2026-10-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0024_alter_registroobservador_subtipo'),
        ('puntoexacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='numero_opciones',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Vacío = las del bloque, o las del examen. Sirve para hojas tipo ICFES, donde unas preguntas son A–D y otras A–H.', null=True, verbose_name='Opciones de esta pregunta'),
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del bloque')),
                ('numero_opciones', models.PositiveSmallIntegerField(blank=True, help_text='Vacío = las del examen.', null=True, verbose_name='Opciones del bloque')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='puntoexacto.examen')),
                ('materia', models.ForeignKey(blank=True, help_text='Opcional. Solo si quiere que la nota de este bloque pueda ir a la planilla de esa asignatura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_puntoexacto', to='notas.materia', verbose_name='Materia del colegio')),
            ],
            options={
                'verbose_name': 'Bloque de examen',
                'verbose_name_plural': 'Bloques de examen',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='puntoexacto.bloque', verbose_name='Bloque o área'),
        ),
    ]
