# Generated by Django 5.2.3 on 2026-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntoexacto', '0002_pregunta_numero_opciones_bloque_pregunta_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='mostrar_docente',
            field=models.BooleanField(default=False, verbose_name='Imprimir el nombre del docente en la hoja'),
        ),
        migrations.AddField(
            model_name='examen',
            name='mostrar_fecha',
            field=models.BooleanField(default=False, verbose_name='Imprimir la fecha de presentación en la hoja'),
        ),
    ]
