# Generated by Django 5.2.3 on 2026-10-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntoexacto", "0005_pregunta_rotulos"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoja",
            name="forma",
            field=models.CharField(default="A", max_length=1),
        ),
        migrations.AddField(
            model_name="hoja",
            name="lectura",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Forma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letra", models.CharField(max_length=1)),
                ("orden", models.JSONField(default=list)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formas",
                        to="puntoexacto.examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forma",
                "verbose_name_plural": "Formas",
                "ordering": ["letra"],
                "unique_together": {("examen", "letra")},
            },
        ),
    ]
