# Generated by Django 5.2.3 on 2026-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntoexacto", "0006_formas"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregunta",
            name="es_control",
            field=models.BooleanField(
                default=False, verbose_name="Pregunta de control"
            ),
        ),
    ]
