# Generated by Django 5.2.3 on 2026-10-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntoexacto", "0007_pregunta_control"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuadernillo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.JSONField(blank=True, default=dict)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "examen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuadernillo",
                        to="puntoexacto.examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuadernillo",
            },
        ),
    ]
