# Generated by Django 5.2.3 on 2026-10-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntoexacto", "0008_cuadernillo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examen",
            name="componente",
            field=models.CharField(
                choices=[
                    ("SER", "SER"),
                    ("SABER", "SABER"),
                    ("HACER", "HACER"),
                    ("C4", "C4"),
                    ("C5", "C5"),
                    ("C6", "C6"),
                    ("C7", "C7"),
                    ("C8", "C8"),
                    ("C9", "C9"),
                    ("C10", "C10"),
                    ("C11", "C11"),
                    ("C12", "C12"),
                ],
                default="SABER",
                help_text="Si alguna pregunta tiene su propio componente, el examen se parte en varias columnas, una por componente.",
                max_length=6,
                verbose_name="A qué columna de la planilla va",
            ),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="componente",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SER", "SER"),
                    ("SABER", "SABER"),
                    ("HACER", "HACER"),
                    ("C4", "C4"),
                    ("C5", "C5"),
                    ("C6", "C6"),
                    ("C7", "C7"),
                    ("C8", "C8"),
                    ("C9", "C9"),
                    ("C10", "C10"),
                    ("C11", "C11"),
                    ("C12", "C12"),
                ],
                help_text="Vacío = el del examen. Permite que un mismo examen evalúe SABER en unas preguntas y HACER en otras.",
                max_length=6,
                verbose_name="Componente",
            ),
        ),
    ]
