# Generated by Django 5.2.3 on 2026-10-08 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notas", "0031_disenos_portal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Acta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COMISION", "Comisión de evaluación y promoción"),
                            ("LIBRE", "Acta libre"),
                        ],
                        default="COMISION",
                        max_length=10,
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Acta N.º")),
                ("ano", models.PositiveIntegerField(verbose_name="Año")),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ej.: Comisión de evaluación y promoción grado sexto",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "hora_inicio",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de inicio"
                    ),
                ),
                (
                    "hora_fin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de cierre"
                    ),
                ),
                (
                    "lugar",
                    models.CharField(blank=True, max_length=200, verbose_name="Lugar"),
                ),
                (
                    "alcance",
                    models.CharField(
                        choices=[
                            ("PERIODO", "Pendientes del periodo"),
                            ("ACUMULADO", "Pendientes en el acumulado del año"),
                        ],
                        default="PERIODO",
                        max_length=10,
                        verbose_name="Asignaturas pendientes",
                    ),
                ),
                (
                    "mostrar_observador",
                    models.BooleanField(
                        default=False,
                        help_text="Al lado de cada estudiante, cuántas anotaciones «a mejorar» tiene en el observador.",
                        verbose_name="Mostrar anotaciones del observador",
                    ),
                ),
                (
                    "orden_del_dia",
                    models.TextField(
                        blank=True,
                        help_text="Un punto por línea.",
                        verbose_name="Orden del día",
                    ),
                ),
                (
                    "desarrollo",
                    models.TextField(
                        blank=True, verbose_name="Desarrollo de la reunión"
                    ),
                ),
                (
                    "decisiones",
                    models.TextField(
                        blank=True,
                        help_text="Uno por línea.",
                        verbose_name="Decisiones y compromisos",
                    ),
                ),
                (
                    "asistentes",
                    models.TextField(
                        blank=True,
                        help_text="Uno por línea: Nombre — Cargo",
                        verbose_name="Asistentes",
                    ),
                ),
                ("informe", models.JSONField(blank=True, editable=False, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("BORRADOR", "Borrador"), ("CERRADA", "Cerrada")],
                        default="BORRADOR",
                        max_length=10,
                    ),
                ),
                ("cerrada_en", models.DateTimeField(blank=True, null=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actas",
                        to="notas.colegio",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cursos",
                    models.ManyToManyField(
                        blank=True, to="notas.curso", verbose_name="Cursos"
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notas.periodoacademico",
                        verbose_name="Periodo",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notas.sede",
                        verbose_name="Sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta",
                "ordering": ["-ano", "-numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("colegio", "ano", "numero"), name="acta_numero_unico"
                    )
                ],
            },
        ),
    ]
