# Generated by Django 5.2.3 on 2026-10-03 21:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0022_alter_colegio_alto_logos_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncalificaciones',
            name='colapsar_area_unica',
            field=models.BooleanField(default=True, help_text='Evita que la sábana y el boletín repitan la misma nota en dos filas.', verbose_name='Unir área y asignatura cuando el área tiene una sola'),
        ),
        migrations.AddField(
            model_name='configuracioncalificaciones',
            name='etiqueta_hacer',
            field=models.CharField(default='HACER', max_length=30, verbose_name='Nombre de la columna 3'),
        ),
        migrations.AddField(
            model_name='configuracioncalificaciones',
            name='etiqueta_saber',
            field=models.CharField(default='SABER', max_length=30, verbose_name='Nombre de la columna 2'),
        ),
        migrations.AddField(
            model_name='configuracioncalificaciones',
            name='etiqueta_ser',
            field=models.CharField(default='SER', max_length=30, verbose_name='Nombre de la columna 1'),
        ),
        migrations.AddField(
            model_name='configuracioncalificaciones',
            name='exigir_periodos_completos',
            field=models.BooleanField(default=False, help_text='En vez de promediar lo que haya, avisa cuáles periodos faltan. Se activa solo cuando se ponderan los periodos.', verbose_name='No calcular la definitiva si falta algún periodo'),
        ),
        migrations.AddField(
            model_name='configuracioncalificaciones',
            name='ponderar_periodos',
            field=models.BooleanField(default=False, help_text='Si se deja apagado, todos los periodos pesan igual, como hasta ahora.', verbose_name='Cada periodo vale un porcentaje distinto'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='peso_porcentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Solo se usa si el colegio activó la ponderación por periodos.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Peso del periodo (%)'),
        ),
    ]
