# Generated by Django 5.2.3 on 2026-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0023_configuracioncalificaciones_colapsar_area_unica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroobservador',
            name='subtipo',
            field=models.CharField(blank=True, choices=[('POSITIVA', 'Positiva'), ('NEGATIVA', 'A Mejorar')], help_text='Positiva o a mejorar. Aplica tanto a convivencia como a académicas.', max_length=10, null=True),
        ),
    ]
