# Generated by Django 5.2.3 on 2026-10-06 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0025_curso_grado_subgrupo_historialmatricula"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colegio",
            name="url_twitter_x",
        ),
        migrations.AddField(
            model_name="colegio",
            name="url_tiktok",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="URL de TikTok"
            ),
        ),
        migrations.AddField(
            model_name="configuracioncalificaciones",
            name="notas_por_componente",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Cuántas columnas trae cada componente (SER, SABER, HACER) en la planilla en línea y en el Excel, si el docente no configuró las suyas.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(15),
                ],
                verbose_name="Notas por componente cuando el docente no elige",
            ),
        ),
        migrations.CreateModel(
            name="PlanNotas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "componente",
                    models.CharField(
                        choices=[
                            ("SER", "SER"),
                            ("SABER", "SABER"),
                            ("HACER", "HACER"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "columnas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Nombres de las notas, en orden: ["Taller 1", "Quiz"…]',
                    ),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "asignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_notas",
                        to="notas.asignaciondocente",
                    ),
                ),
                (
                    "colegio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_notas",
                        to="notas.colegio",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_notas",
                        to="notas.periodoacademico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de notas",
                "verbose_name_plural": "Planes de notas",
                "unique_together": {("asignacion", "periodo", "componente")},
            },
        ),
    ]
