# Generated by Django 5.2.3 on 2026-10-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0027_administrador_colegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('MENSAJE', 'Nuevo Mensaje'), ('OBSERVADOR', 'Observación Registrada'), ('PERIODO', 'Cambio en Periodo'), ('RENDIMIENTO', 'Alerta de Rendimiento'), ('GENERAL', 'Aviso General')], default='GENERAL', max_length=15),
        ),
        migrations.DeleteModel(
            name='AdministradorColegio',
        ),
    ]
