# Generated by Django 5.2.3 on 2026-10-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0028_calificacion_observacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej.: Sede Principal, Sede Simón Bolívar.",
                        max_length=120,
                        verbose_name="Nombre de la sede",
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, verbose_name="Es la sede principal"
                    ),
                ),
                (
                    "codigo_dane",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código DANE de la sede"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "barrio",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Barrio / vereda"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Teléfono"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo"
                    ),
                ),
                (
                    "encargado",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Coordinador o encargado",
                    ),
                ),
                (
                    "jornadas",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Jornadas"
                    ),
                ),
                (
                    "niveles",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Niveles que ofrece"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, verbose_name="Descripción para el portal"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sedes/",
                        verbose_name="Foto de la sede",
                    ),
                ),
                (
                    "enlace_mapa",
                    models.URLField(
                        blank=True,
                        help_text="Abra la sede en Google Maps, toque «Compartir» y pegue el enlace.",
                        max_length=500,
                        verbose_name="Enlace de Google Maps",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Las inactivas no salen en el portal ni en los filtros.",
                        verbose_name="Activa",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sedes",
                        to="notas.colegio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "ordering": ["-es_principal", "orden", "nombre"],
                "unique_together": {("colegio", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to="notas.sede",
                verbose_name="Sede",
            ),
        ),
    ]
