# Generated by Django 5.2.3 on 2026-10-06 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0028_alter_notificacion_tipo_delete_administradorcolegio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('MENSAJE', 'Nuevo Mensaje'), ('OBSERVADOR', 'Observación Registrada'), ('PERIODO', 'Cambio en Periodo'), ('RENDIMIENTO', 'Alerta de Rendimiento'), ('GENERAL', 'Aviso General'), ('PLANILLA', 'Cambio en la planilla')], default='GENERAL', max_length=15),
        ),
        migrations.CreateModel(
            name='AdministradorColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('RECTOR', 'Rector(a)'), ('COORDINADOR', 'Coordinador(a)'), ('SECRETARIA', 'Secretaría académica'), ('ADMINISTRATIVO', 'Administrativo'), ('OTRO', 'Otro')], default='ADMINISTRATIVO', max_length=15)),
                ('activo', models.BooleanField(default=True, help_text='Desmárquelo para quitarle el acceso sin borrar el registro.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='notas.colegio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador del colegio',
                'verbose_name_plural': 'Administradores del colegio',
                'ordering': ['colegio__nombre', 'user__last_name'],
                'unique_together': {('user', 'colegio')},
            },
        ),
    ]
