# Generated by Django 5.2.3 on 2026-10-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0029_sedes"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroobservador",
            name="acudiente_enterado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Acudiente enterado el"
            ),
        ),
        migrations.AddField(
            model_name="registroobservador",
            name="descargo_acudiente",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Descargo o comentario del acudiente",
            ),
        ),
        migrations.AddField(
            model_name="registroobservador",
            name="firma_acudiente",
            field=models.CharField(
                blank=True,
                default="",
                max_length=160,
                verbose_name="Quién firmó como enterado",
            ),
        ),
    ]
