# Generated by Django 5.2.3 on 2026-10-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0030_respuesta_acudiente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colegio",
            name="layout_portal",
            field=models.CharField(
                choices=[
                    ("topbar", "Clásico: barra de navegación superior"),
                    ("sidebar", "Lateral: menú a la izquierda"),
                    ("franja", "Institucional: franja de contacto y menú centrado"),
                    ("portada", "Portada: imagen grande de bienvenida"),
                    ("mosaico", "Mosaico: bloques de colores en la página de inicio"),
                    ("minimal", "Minimalista: limpio y con mucho espacio"),
                    ("revista", "Revista: noticias destacadas como un periódico"),
                ],
                default="topbar",
                max_length=10,
                verbose_name="Diseño del Portal",
            ),
        ),
    ]
