# Generated by Django 5.2.3 on 2026-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0031_disenos_portal"),
    ]

    operations = [
        migrations.AddField(
            model_name="colegio",
            name="linea_encabezado_5",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Línea 5 del Encabezado",
            ),
        ),
        migrations.AddField(
            model_name="colegio",
            name="linea_encabezado_5_cursiva",
            field=models.BooleanField(default=False, verbose_name="Cursiva L5"),
        ),
        migrations.AddField(
            model_name="colegio",
            name="linea_encabezado_5_fuente",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica (Estándar)"),
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Courier", "Courier (Máquina de escribir)"),
                    ("Verdana", "Verdana"),
                    ("Georgia", "Georgia"),
                    ("Garamond", "Garamond"),
                    ("Tahoma", "Tahoma"),
                    ("Game On_PersonalUseOnly", "Game On (Personalizada)"),
                ],
                default="Helvetica",
                max_length=100,
                verbose_name="Fuente L5",
            ),
        ),
        migrations.AddField(
            model_name="colegio",
            name="linea_encabezado_5_negrilla",
            field=models.BooleanField(default=False, verbose_name="Negrilla L5"),
        ),
        migrations.AddField(
            model_name="colegio",
            name="linea_encabezado_5_subrayado",
            field=models.BooleanField(default=False, verbose_name="Subrayado L5"),
        ),
        migrations.AddField(
            model_name="colegio",
            name="linea_encabezado_5_tamano",
            field=models.PositiveSmallIntegerField(
                default=8, verbose_name="Tamaño L5 (pt)"
            ),
        ),
        migrations.AlterField(
            model_name="colegio",
            name="fuente_firma_rector",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica (Estándar)"),
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Courier", "Courier (Máquina de escribir)"),
                    ("Verdana", "Verdana"),
                    ("Georgia", "Georgia"),
                    ("Garamond", "Garamond"),
                    ("Tahoma", "Tahoma"),
                    ("Game On_PersonalUseOnly", "Game On (Personalizada)"),
                ],
                default="Helvetica",
                max_length=100,
                verbose_name="Fuente de la Firma del Rector",
            ),
        ),
        migrations.AlterField(
            model_name="colegio",
            name="linea_encabezado_1_fuente",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica (Estándar)"),
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Courier", "Courier (Máquina de escribir)"),
                    ("Verdana", "Verdana"),
                    ("Georgia", "Georgia"),
                    ("Garamond", "Garamond"),
                    ("Tahoma", "Tahoma"),
                    ("Game On_PersonalUseOnly", "Game On (Personalizada)"),
                ],
                default="Helvetica",
                max_length=100,
                verbose_name="Fuente L1",
            ),
        ),
        migrations.AlterField(
            model_name="colegio",
            name="linea_encabezado_2_fuente",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica (Estándar)"),
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Courier", "Courier (Máquina de escribir)"),
                    ("Verdana", "Verdana"),
                    ("Georgia", "Georgia"),
                    ("Garamond", "Garamond"),
                    ("Tahoma", "Tahoma"),
                    ("Game On_PersonalUseOnly", "Game On (Personalizada)"),
                ],
                default="Helvetica",
                max_length=100,
                verbose_name="Fuente L2",
            ),
        ),
        migrations.AlterField(
            model_name="colegio",
            name="linea_encabezado_3_fuente",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica (Estándar)"),
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Courier", "Courier (Máquina de escribir)"),
                    ("Verdana", "Verdana"),
                    ("Georgia", "Georgia"),
                    ("Garamond", "Garamond"),
                    ("Tahoma", "Tahoma"),
                    ("Game On_PersonalUseOnly", "Game On (Personalizada)"),
                ],
                default="Helvetica",
                max_length=100,
                verbose_name="Fuente L3",
            ),
        ),
        migrations.AlterField(
            model_name="colegio",
            name="linea_encabezado_4_fuente",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica (Estándar)"),
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Courier", "Courier (Máquina de escribir)"),
                    ("Verdana", "Verdana"),
                    ("Georgia", "Georgia"),
                    ("Garamond", "Garamond"),
                    ("Tahoma", "Tahoma"),
                    ("Game On_PersonalUseOnly", "Game On (Personalizada)"),
                ],
                default="Helvetica",
                max_length=100,
                verbose_name="Fuente L4",
            ),
        ),
    ]
