# Generated by Django 5.2.3 on 2026-10-08 18:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0032_encabezado_linea5_tahoma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="valor_nota",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="escalavaloracion",
            name="valor_maximo",
            field=models.DecimalField(
                decimal_places=1, max_digits=4, verbose_name="Valor Máximo"
            ),
        ),
        migrations.AlterField(
            model_name="escalavaloracion",
            name="valor_minimo",
            field=models.DecimalField(
                decimal_places=1, max_digits=4, verbose_name="Valor Mínimo"
            ),
        ),
        migrations.AlterField(
            model_name="notadetallada",
            name="valor_nota",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
