# Generated by Django 5.2.3 on 2026-10-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0033_notas_segun_escala"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioncalificaciones",
            name="abreviatura_hacer",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                verbose_name="Abreviatura de la columna 3",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncalificaciones",
            name="abreviatura_saber",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                verbose_name="Abreviatura de la columna 2",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncalificaciones",
            name="abreviatura_ser",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                verbose_name="Abreviatura de la columna 1",
            ),
        ),
    ]
