# Generated by Django 5.2.3 on 2026-10-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0034_abreviaturas_componentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignaciondocente",
            name="pesos_componentes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Porcentajes por componente"
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="pesos_componentes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Porcentajes por componente"
            ),
        ),
        migrations.AlterField(
            model_name="calificacion",
            name="tipo_nota",
            field=models.CharField(
                choices=[
                    ("SER", "Promedio Ser"),
                    ("SABER", "Promedio Saber"),
                    ("HACER", "Promedio Hacer"),
                    ("C4", "Promedio componente 4"),
                    ("C5", "Promedio componente 5"),
                    ("C6", "Promedio componente 6"),
                    ("C7", "Promedio componente 7"),
                    ("C8", "Promedio componente 8"),
                    ("C9", "Promedio componente 9"),
                    ("C10", "Promedio componente 10"),
                    ("C11", "Promedio componente 11"),
                    ("C12", "Promedio componente 12"),
                    ("PROM_PERIODO", "Promedio del Periodo"),
                    ("NIVELACION", "Nota de Nivelación"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="plannotas",
            name="componente",
            field=models.CharField(
                choices=[
                    ("SER", "SER"),
                    ("SABER", "SABER"),
                    ("HACER", "HACER"),
                    ("C4", "C4"),
                    ("C5", "C5"),
                    ("C6", "C6"),
                    ("C7", "C7"),
                    ("C8", "C8"),
                    ("C9", "C9"),
                    ("C10", "C10"),
                    ("C11", "C11"),
                    ("C12", "C12"),
                ],
                max_length=6,
            ),
        ),
        migrations.CreateModel(
            name="ComponenteEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("SER", "SER"),
                            ("SABER", "SABER"),
                            ("HACER", "HACER"),
                            ("C4", "C4"),
                            ("C5", "C5"),
                            ("C6", "C6"),
                            ("C7", "C7"),
                            ("C8", "C8"),
                            ("C9", "C9"),
                            ("C10", "C10"),
                            ("C11", "C11"),
                            ("C12", "C12"),
                        ],
                        max_length=6,
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "abreviatura",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("orden", models.PositiveSmallIntegerField(default=1)),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes_evaluacion",
                        to="notas.colegio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente de evaluación",
                "verbose_name_plural": "Componentes de evaluación",
                "ordering": ["orden", "id"],
                "unique_together": {("colegio", "codigo")},
            },
        ),
    ]
