# Generated by Django 5.2.3 on 2026-10-09 01:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0035_componentes_dinamicos"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecursoEducativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Descripción breve"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        help_text="Agrupa los recursos en el portal. Ej.: Plataformas gratuitas, Guías de grado 6.°",
                        max_length=80,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "enlace",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Enlace (opcional)"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to="recursos_portal/",
                        verbose_name="Archivo (opcional)",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True, verbose_name="Visible en el portal"
                    ),
                ),
                ("creado", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos_educativos",
                        to="notas.colegio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso educativo",
                "verbose_name_plural": "Recursos educativos",
                "ordering": ["categoria", "orden", "titulo"],
            },
        ),
    ]
