# Generated by Django 5.2.3 on 2026-10-09 14:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0036_recursos_educativos"),
    ]

    operations = [
        migrations.CreateModel(
            name="PonderacionGrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grado", models.SmallIntegerField()),
                (
                    "peso_porcentual",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notas.areaconocimiento",
                    ),
                ),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ponderaciones_grado",
                        to="notas.colegio",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notas.materia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponderación por grado",
                "verbose_name_plural": "Ponderaciones por grado",
                "unique_together": {("colegio", "area", "materia", "grado")},
            },
        ),
    ]
