# Generated by Django 5.2.3 on 2026-10-09 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0037_ponderacion_por_grado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fotogaleria",
            name="embed",
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="fotogaleria",
            name="enlace",
            field=models.CharField(blank=True, max_length=500, verbose_name="Enlace"),
        ),
        migrations.AddField(
            model_name="fotogaleria",
            name="fuente",
            field=models.CharField(
                choices=[
                    ("archivo", "Archivo subido"),
                    ("drive", "Google Drive"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                ],
                default="archivo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fotogaleria",
            name="imagen_externa",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="fotogaleria",
            name="imagen",
            field=models.ImageField(
                blank=True, upload_to="galeria_portal/", verbose_name="Fotografía"
            ),
        ),
        migrations.CreateModel(
            name="VideoPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        max_length=600,
                        verbose_name="Descripción (opcional)",
                    ),
                ),
                (
                    "enlace",
                    models.CharField(max_length=500, verbose_name="Enlace del video"),
                ),
                (
                    "proveedor",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("vimeo", "Vimeo"),
                            ("drive", "Google Drive"),
                            ("facebook", "Facebook"),
                        ],
                        max_length=10,
                    ),
                ),
                ("video_id", models.CharField(max_length=200)),
                ("embed", models.URLField(max_length=600)),
                ("miniatura", models.URLField(blank=True, max_length=300)),
                (
                    "destacado",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar en la página de inicio"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Publicado"),
                ),
                ("creado", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos_portal",
                        to="notas.colegio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video del portal",
                "verbose_name_plural": "Videos del portal",
                "ordering": ["-creado"],
            },
        ),
    ]
