# Generated by Django 5.2.3 on 2026-10-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0038_videos_y_fotos_por_enlace"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentopublico",
            name="enlace",
            field=models.URLField(blank=True, max_length=500, verbose_name="Enlace"),
        ),
        migrations.AddField(
            model_name="imagencarrusel",
            name="imagen_enlace",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="noticia",
            name="imagen_enlace",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sede",
            name="foto_enlace",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="documentopublico",
            name="archivo",
            field=models.FileField(
                blank=True,
                upload_to="documentos_publicos/",
                verbose_name="Archivo (PDF, Word, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="imagencarrusel",
            name="imagen",
            field=models.ImageField(
                blank=True, upload_to="carrusel_portal/", verbose_name="Imagen de fondo"
            ),
        ),
    ]
