# Generated by Django 5.2.3 on 2026-10-03 13:02

import django.db.models.deletion
import salon_digital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_digital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginapublicada',
            name='comentarios',
            field=models.CharField(choices=[('no', 'Sin comentarios'), ('abiertos', 'Cualquiera comenta y se ve enseguida'), ('moderados', 'Los comentarios esperan tu aprobación')], default='no', max_length=10, verbose_name='Comentarios en la página'),
        ),
        migrations.AddField(
            model_name='paginapublicada',
            name='compartir_classroom',
            field=models.BooleanField(default=True, verbose_name='Mostrar el botón de Google Classroom'),
        ),
        migrations.AddField(
            model_name='paginapublicada',
            name='identificacion',
            field=models.CharField(choices=[('libre', 'El estudiante escribe su nombre'), ('opcional', 'Puede entrar por grupo o escribir su nombre'), ('grupo', 'Solo quien esté en un grupo')], default='opcional', max_length=8, verbose_name='Cómo se identifica el estudiante'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='grupo_texto',
            field=models.CharField(blank=True, max_length=30, verbose_name='Grupo escrito a mano'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 7-01', max_length=60, verbose_name='Nombre del grupo')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('codigo', models.CharField(default=salon_digital.models.codigo_grupo, help_text='El que les dictas a los estudiantes la primera vez.', max_length=8, unique=True, verbose_name='Código para entrar')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='salon_digital.cuenta')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nombre'],
                'unique_together': {('propietario', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='paginapublicada',
            name='grupos',
            field=models.ManyToManyField(blank=True, help_text='Déjalo vacío para aceptar cualquier grupo tuyo.', related_name='paginas', to='salon_digital.grupo', verbose_name='Grupos que pueden entrar'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='salon_digital.grupo'),
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=120)),
                ('nombres', models.CharField(max_length=120)),
                ('completo', models.CharField(blank=True, editable=False, max_length=240)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='salon_digital.grupo')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='sesion',
            name='integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='salon_digital.integrante'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Quién comenta')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('aprobado', models.BooleanField(default=True)),
                ('del_autor', models.BooleanField(default=False, help_text='Lo escribió el dueño de la página.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_comentarios', to='salon_digital.paginapublicada')),
                ('responde_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='salon_digital.comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['pagina', 'creado_en'], name='salon_digit_pagina__dea8be_idx')],
            },
        ),
    ]
