# Generated by Django 5.2.3 on 2026-10-08 05:08

import django.db.models.deletion
import prematricula.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notas", "0029_sedes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abierta",
                    models.BooleanField(
                        default=False,
                        help_text="Mientras esté abierta, sale en el portal del colegio.",
                        verbose_name="Prematrícula abierta",
                    ),
                ),
                (
                    "ano_lectivo",
                    models.PositiveSmallIntegerField(
                        verbose_name="Año lectivo al que se matricula"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateField(
                        blank=True,
                        help_text="Opcional. Después de esta fecha no se reciben solicitudes.",
                        null=True,
                        verbose_name="Fecha de cierre",
                    ),
                ),
                (
                    "permite_antiguos",
                    models.BooleanField(
                        default=True,
                        help_text="Confirman cupo y actualizan sus datos.",
                        verbose_name="Recibir también a estudiantes antiguos",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        blank=True,
                        help_text="Lo que lee la familia antes de empezar: fechas, costos, horarios…",
                        verbose_name="Mensaje de bienvenida",
                    ),
                ),
                (
                    "tratamiento_datos",
                    models.TextField(
                        blank=True,
                        help_text="Texto que la familia acepta (Ley 1581 de 2012). Si lo deja vacío se usa uno general.",
                        verbose_name="Autorización de tratamiento de datos",
                    ),
                ),
                (
                    "colegio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prematricula",
                        to="notas.colegio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de prematrícula",
            },
        ),
        migrations.CreateModel(
            name="PreguntaEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=250, verbose_name="Pregunta")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("UNA", "Una opción"),
                            ("VARIAS", "Varias opciones"),
                            ("SINO", "Sí / No"),
                            ("ESCALA", "Escala de 1 a 5"),
                            ("TEXTO", "Respuesta abierta"),
                        ],
                        default="UNA",
                        max_length=8,
                    ),
                ),
                (
                    "opciones",
                    models.TextField(
                        blank=True,
                        help_text="Para «una» o «varias» opciones: una opción por línea.",
                    ),
                ),
                ("obligatoria", models.BooleanField(default=False)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas_prematricula",
                        to="notas.colegio",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="Requisito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Indicación para la familia",
                    ),
                ),
                (
                    "pide_archivo",
                    models.BooleanField(
                        default=True, verbose_name="La familia sube un archivo"
                    ),
                ),
                ("obligatorio", models.BooleanField(default=True)),
                (
                    "para",
                    models.CharField(
                        choices=[
                            ("TODOS", "Todos"),
                            ("NUEVOS", "Solo estudiantes nuevos"),
                            ("ANTIGUOS", "Solo antiguos"),
                        ],
                        default="TODOS",
                        max_length=10,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos_prematricula",
                        to="notas.colegio",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano_lectivo", models.PositiveSmallIntegerField()),
                ("radicado", models.CharField(max_length=20, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NUEVO", "Estudiante nuevo"),
                            ("ANTIGUO", "Estudiante antiguo"),
                        ],
                        default="NUEVO",
                        max_length=8,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RECIBIDA", "Recibida"),
                            ("REVISION", "En revisión"),
                            ("PENDIENTE", "Falta algo"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "No aprobada"),
                        ],
                        default="RECIBIDA",
                        max_length=10,
                    ),
                ),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("actualizada", models.DateTimeField(auto_now=True)),
                (
                    "grado",
                    models.SmallIntegerField(
                        choices=[
                            (
                                "Preescolar",
                                [(-2, "Prejardín"), (-1, "Jardín"), (0, "Transición")],
                            ),
                            (
                                "Primaria",
                                [
                                    (1, "Primero"),
                                    (2, "Segundo"),
                                    (3, "Tercero"),
                                    (4, "Cuarto"),
                                    (5, "Quinto"),
                                ],
                            ),
                            (
                                "Básica Secundaria",
                                [
                                    (6, "Sexto"),
                                    (7, "Séptimo"),
                                    (8, "Octavo"),
                                    (9, "Noveno"),
                                ],
                            ),
                            ("Media", [(10, "Décimo"), (11, "Undécimo")]),
                        ],
                        verbose_name="Grado al que se matricula",
                    ),
                ),
                (
                    "jornada",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Jornada de preferencia"
                    ),
                ),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("RC", "Registro civil"),
                            ("TI", "Tarjeta de identidad"),
                            ("CC", "Cédula de ciudadanía"),
                            ("CE", "Cédula de extranjería"),
                            ("PPT", "Permiso por protección temporal"),
                            ("OT", "Otro"),
                        ],
                        default="TI",
                        max_length=3,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20)),
                ("fecha_nacimiento", models.DateField()),
                ("lugar_nacimiento", models.CharField(blank=True, max_length=120)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Femenino"),
                            ("M", "Masculino"),
                            ("O", "Otro"),
                            ("N", "Prefiere no decir"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Dirección de residencia",
                    ),
                ),
                (
                    "barrio",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Barrio / vereda"
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=40)),
                ("colegio_procedencia", models.CharField(blank=True, max_length=200)),
                (
                    "ultimo_grado",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Último grado cursado"
                    ),
                ),
                (
                    "eps",
                    models.CharField(blank=True, max_length=120, verbose_name="EPS"),
                ),
                (
                    "rh",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        verbose_name="Grupo sanguíneo y RH",
                    ),
                ),
                (
                    "alergias",
                    models.TextField(
                        blank=True, verbose_name="Enfermedades, alergias o medicamentos"
                    ),
                ),
                (
                    "necesita_apoyo",
                    models.BooleanField(
                        default=False,
                        verbose_name="Requiere apoyo pedagógico o de inclusión",
                    ),
                ),
                (
                    "apoyo_detalle",
                    models.CharField(blank=True, max_length=300, verbose_name="Cuál"),
                ),
                (
                    "emergencia_nombre",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Contacto de emergencia",
                    ),
                ),
                (
                    "emergencia_telefono",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Teléfono de emergencia"
                    ),
                ),
                (
                    "emergencia_parentesco",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Parentesco"
                    ),
                ),
                (
                    "acudiente_nombre",
                    models.CharField(
                        max_length=160, verbose_name="Nombre del acudiente"
                    ),
                ),
                (
                    "acudiente_documento",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Documento del acudiente",
                    ),
                ),
                (
                    "acudiente_parentesco",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Parentesco"
                    ),
                ),
                (
                    "acudiente_celular",
                    models.CharField(
                        max_length=40, verbose_name="Celular del acudiente"
                    ),
                ),
                (
                    "acudiente_correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo del acudiente"
                    ),
                ),
                (
                    "acudiente_ocupacion",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Ocupación"
                    ),
                ),
                (
                    "madre_nombre",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Nombre de la madre"
                    ),
                ),
                (
                    "madre_celular",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Celular de la madre"
                    ),
                ),
                (
                    "padre_nombre",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Nombre del padre"
                    ),
                ),
                (
                    "padre_celular",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Celular del padre"
                    ),
                ),
                ("acepta_datos", models.BooleanField(default=False)),
                ("encuesta", models.JSONField(blank=True, default=dict)),
                (
                    "checklist",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{id de requisito: true/false} marcado por la secretaría.",
                    ),
                ),
                (
                    "nota_interna",
                    models.TextField(
                        blank=True, verbose_name="Notas internas de la revisión"
                    ),
                ),
                (
                    "mensaje_familia",
                    models.TextField(
                        blank=True,
                        help_text="Lo ve la familia al consultar su solicitud.",
                        verbose_name="Mensaje para la familia",
                    ),
                ),
                ("decidida", models.DateTimeField(blank=True, null=True)),
                (
                    "colegio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_prematricula",
                        to="notas.colegio",
                    ),
                ),
                (
                    "curso_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prematriculas",
                        to="notas.curso",
                    ),
                ),
                (
                    "estudiante_antiguo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prematriculas",
                        to="notas.estudiante",
                    ),
                ),
                (
                    "estudiante_creado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="notas.estudiante",
                    ),
                ),
                (
                    "revisada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notas.sede",
                        verbose_name="Sede de preferencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de prematrícula",
                "verbose_name_plural": "Solicitudes de prematrícula",
                "ordering": ["-creada"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        storage=prematricula.models.almacenamiento_privado,
                        upload_to=prematricula.models._ruta_documento,
                    ),
                ),
                ("nombre_original", models.CharField(blank=True, max_length=200)),
                ("subido", models.DateTimeField(auto_now_add=True)),
                (
                    "requisito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prematricula.requisito",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="prematricula.solicitud",
                    ),
                ),
            ],
            options={
                "ordering": ["requisito__orden", "id"],
            },
        ),
    ]
